name       : gsl
version    : '2.4'
release    : 4
source     :
    - ftp://ftp.gnu.org/gnu/gsl/gsl-2.4.tar.gz : 4d46d07b946e7b31c19bbf33dda6204d7bedc2f5462a1bae1d4013426cd1ce9b
homepage   : http://www.gnu.org/software/gsl
license    : GPL-3.0
component  : programming.library
summary    : Numerical library for C and C++
description: |
    GNU Scientific Library is a numerical library for C and C++ programmers. The library provides a wide range of mathematical routines such as random number generators, special functions, and least squares fitting.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
