name       : gsl
version    : '2.6'
release    : 6
source     :
    - https://ftp.gnu.org/gnu/gsl/gsl-2.6.tar.gz : b782339fc7a38fe17689cb39966c4d821236c28018b6593ddb6fd59ee40786a8
homepage   : http://www.gnu.org/software/gsl
license    : GPL-3.0-only
component  : programming.library
summary    : Numerical library for C and C++
description: |
    GNU Scientific Library is a numerical library for C and C++ programmers. The library provides a wide range of mathematical routines such as random number generators, special functions, and least squares fitting.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
